import {headers, sa, ga} from './lib.mjs';
const [S,E]=process.argv.slice(2).length===2?process.argv.slice(2):['2026-08-29','2026-09-26'];
const H=await headers(); const G=await headers('https://www.googleapis.com/auth/analytics.readonly');
const q=b=>sa(H,{startDate:S,endDate:E,rowLimit:200,...b});
const Q=await q({dimensions:['query']}); const P=await q({dimensions:['page']});
const tot=(Q.rows||[]).reduce((a,r)=>[a[0]+r.impressions,a[1]+r.clicks],[0,0]);
console.log(`WINDOW ${S}..${E}  impressions/clicks ${tot.join('/')}`);
console.log('\nTOP QUERIES BY CLICKS (query | impr | clicks | pos)');
for(const r of (Q.rows||[]).filter(r=>r.clicks>0).sort((a,b)=>b.clicks-a.clicks)) console.log(' ',r.keys[0].slice(0,60).padEnd(60),r.impressions,r.clicks,r.position.toFixed(1));
console.log('\nTOP NON-BRAND QUERIES BY IMPRESSIONS (0 clicks unless shown)');
for(const r of (Q.rows||[]).filter(r=>!/shimmer/i.test(r.keys[0])).sort((a,b)=>b.impressions-a.impressions).slice(0,30)) console.log(' ',r.keys[0].slice(0,70).padEnd(70),r.impressions,r.clicks,r.position.toFixed(1));
console.log('\nQUERIES ON PAGE 1 (pos<=10) WITH 0 CLICKS: snippet/title problem candidates');
for(const r of (Q.rows||[]).filter(r=>r.position<=10&&r.clicks===0&&r.impressions>=3).sort((a,b)=>b.impressions-a.impressions).slice(0,20)) console.log(' ',r.keys[0].slice(0,70).padEnd(70),r.impressions,r.position.toFixed(1));
console.log('\nQUERIES POS 11-25 WITH IMPRESSIONS: one push from page 1');
for(const r of (Q.rows||[]).filter(r=>r.position>10&&r.position<=25&&r.impressions>=3).sort((a,b)=>b.impressions-a.impressions).slice(0,20)) console.log(' ',r.keys[0].slice(0,70).padEnd(70),r.impressions,r.position.toFixed(1));
console.log('\nTOP PAGES (impr/clicks/pos)');
for(const r of (P.rows||[]).sort((a,b)=>b.impressions-a.impressions).slice(0,25)) console.log(' ',r.keys[0].replace('https://shimmerlabs.co','').padEnd(50),r.impressions,r.clicks,r.position.toFixed(1));
const D=await q({dimensions:['device']}); console.log('\nDEVICE', (D.rows||[]).map(r=>`${r.keys[0]}=${r.impressions}/${r.clicks}`).join('  '));
const C=await q({dimensions:['country']}); console.log('COUNTRY', (C.rows||[]).slice(0,5).map(r=>`${r.keys[0]}=${r.impressions}/${r.clicks}`).join('  '));
// GA4: sessions by source/medium and landing page, 30 days; plus AI referrals
const rep=b=>ga(G,{dateRanges:[{startDate:S,endDate:E}],...b});
const sm=await rep({dimensions:[{name:'sessionSourceMedium'}],metrics:[{name:'sessions'},{name:'engagedSessions'},{name:'keyEvents'}],orderBys:[{metric:{metricName:'sessions'},desc:true}],limit:15});
console.log('\nGA4 SOURCE/MEDIUM (sessions/engaged/keyEvents)'); for(const r of sm.rows||[]) console.log(' ',r.dimensionValues[0].value.padEnd(40),r.metricValues.map(m=>m.value).join('/'));
const lp=await rep({dimensions:[{name:'landingPage'},{name:'sessionDefaultChannelGroup'}],metrics:[{name:'sessions'}],dimensionFilter:{filter:{fieldName:'sessionDefaultChannelGroup',stringFilter:{matchType:'EXACT',value:'Organic Search'}}},orderBys:[{metric:{metricName:'sessions'},desc:true}],limit:15});
console.log('\nGA4 ORGANIC LANDING PAGES'); for(const r of lp.rows||[]) console.log(' ',r.metricValues[0].value.padStart(3),r.dimensionValues[0].value);
const ev=await rep({dimensions:[{name:'eventName'}],metrics:[{name:'eventCount'}],dimensionFilter:{orGroup:{expressions:['scan','form','intake','lead','click','cta'].map(v=>({filter:{fieldName:'eventName',stringFilter:{matchType:'CONTAINS',value:v}}}))}}});
console.log('\nGA4 FUNNEL EVENTS 30d', (ev.rows||[]).map(r=>`${r.dimensionValues[0].value}=${r.metricValues[0].value}`).join(', ')||'none');
const ai=await rep({dimensions:[{name:'sessionSource'},{name:'landingPage'}],metrics:[{name:'sessions'}],dimensionFilter:{orGroup:{expressions:['chatgpt','perplexity','gemini','copilot','claude','openai','bing.com'].map(v=>({filter:{fieldName:'sessionSource',stringFilter:{matchType:'CONTAINS',value:v}}}))}}});
console.log('GA4 AI/ASSISTANT REFERRALS 30d', (ai.rows||[]).map(r=>`${r.dimensionValues[0].value} -> ${r.dimensionValues[1].value} (${r.metricValues[0].value})`).join('; ')||'none');
